image:
  repository: placeholder
  tag: placeholder
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  SECRET_KEY: changeme
  DEBUG: "False"

  DB_NAME: placeholder
  DB_USER: placeholder
  DB_PASSWORD: placeholder
  DB_HOST: placeholder
  DB_PORT: placeholder

migrations:
  enabled: false

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
