image:
  repository: fredisson11/tp154-api
  tag:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  DB_NAME:
  DB_USER:
  DB_PASSWORD:
  DB_HOST:
  DB_PORT:

migrations:
  enabled: false

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
